import type { Receipt } from '@/types/receipt';

export const demoReceipt: Receipt = {
  id: 'demo-1',
  receipt_number: 'GEN-2026-000001',
  register_id: 'demo-reg',
  register: {
    id: 'demo-reg',
    code: 'GEN',
    name_ar: 'السجل العام',
    name_en: 'General Register',
    description: null,
    fiscal_year: 2026,
    is_active: true,
    current_sequence: 1,
  },
  created_by: {
    id: 'demo-user',
    name: 'أحمد محمد',
    username: 'ahmed',
    email: 'ahmed@example.com',
    is_active: true,
    roles: [{ id: '1', name: 'cashier' }],
    permissions: ['view-receipt', 'create-receipt'],
    last_login_at: null,
  },
  total_amount: '125000.00',
  status: 'issued',
  version: 1,
  notes: 'وصل تجريبي للمعاينة',
  qr_payload: JSON.stringify({ hash: 'a1b2c3d4e5f67890', receipt_id: 'demo-1' }),
  printed_at: null,
  cancelled_at: null,
  cancel_reason: null,
  items: [
    {
      id: 'item-1',
      receipt_id: 'demo-1',
      field_id: 'field-1',
      field_name_snapshot: 'service_type',
      label_ar_snapshot: 'نوع الخدمة',
      amount: null,
      text_value: 'رسوم تجديد رخصة',
    },
    {
      id: 'item-2',
      receipt_id: 'demo-1',
      field_id: 'field-2',
      field_name_snapshot: 'amount',
      label_ar_snapshot: 'المبلغ الأساسي',
      amount: '100000.00',
      text_value: null,
    },
    {
      id: 'item-3',
      receipt_id: 'demo-1',
      field_id: 'field-3',
      field_name_snapshot: 'tax',
      label_ar_snapshot: 'الضريبة',
      amount: '15000.00',
      text_value: null,
    },
    {
      id: 'item-4',
      receipt_id: 'demo-1',
      field_id: 'field-4',
      field_name_snapshot: 'fees',
      label_ar_snapshot: 'رسوم إدارية',
      amount: '10000.00',
      text_value: null,
    },
  ],
  created_at: '2026-05-26T10:30:00.000000Z',
  updated_at: '2026-05-26T10:30:00.000000Z',
};
