<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            direction: rtl;
            text-align: right;
            margin: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #2c3e50;
            margin: 0;
            font-size: 24px;
        }
        .meta {
            font-size: 12px;
            color: #666;
            margin-top: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th {
            background-color: #3498db;
            color: white;
            padding: 10px;
            border: 1px solid #2980b9;
            font-size: 13px;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
            font-size: 12px;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .aggregations {
            margin-top: 30px;
            border: 1px solid #ddd;
            padding: 15px;
            background-color: #f8f9fa;
        }
        .aggregations h3 {
            margin-top: 0;
            color: #2c3e50;
        }
        .agg-item {
            display: inline-block;
            margin: 10px 20px;
            padding: 10px 15px;
            background-color: #3498db;
            color: white;
            border-radius: 5px;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report['name'] ?? 'Report' }}</h1>
        <div class="meta">
            <div>Generated: {{ $generated_at->format('Y-m-d H:i:s') }}</div>
            <div>By: {{ $metadata['generated_by'] ?? 'System' }}</div>
        </div>
    </div>

    @if(!empty($data))
    <table>
        <thead>
            <tr>
                @foreach(array_keys($data[0]) as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
                <tr>
                    @foreach($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p style="text-align: center; color: #999; padding: 40px;">No data available</p>
    @endif

    @if(!empty($aggregations))
    <div class="aggregations">
        <h3>Summary Statistics</h3>
        @foreach($aggregations as $agg)
            <div class="agg-item">
                <strong>{{ $agg['alias'] ?? $agg['field'] }}:</strong> 
                {{ number_format($agg['value'], 2) }}
                @if($agg['format'] === 'currency') د.ع @endif
                @if($agg['format'] === 'percentage')% @endif
            </div>
        @endforeach
    </div>
    @endif

    <div class="footer">
        <div>Page 1 of 1</div>
        <div>Generated by Government Financial Platform - Report Engine</div>
    </div>
</body>
</html>
